// PRODUCTS
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PAGINATED_PRODUCTS = "SET_PAGINATED_PRODUCTS";

// CART
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const UPDATE_PRODUCT_COUNT_IN_CART = "UPDATE_PRODUCT_COUNT_IN_CART";
